### ISSUE TITLE
JWT authentication does not work

### ISSUE THREAD

**Issue by kickbox** [robbiet480/go-wordpress#1]
I am not able make this example work for me. https://github.com/robbiet480/go-wordpress/blob/master/example/oauth2/main.go.

I get 403 error 

`403 Wrong number of segments exit status 1 `

Is it still working? I used the exact code as per your example.

```
func main() {
	ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: "JWT_TOKEN"},
	)
	tc := oauth2.NewClient(ctx, ts)

	client, _ := wordpress.NewClient("http://asdasd.com/wp-json/", tc)

	// get the currently authenticated users details
	authenticatedUser, _, err := client.Users.Me(ctx, nil)
	if err != nil {
		log.Fatalln(err)
	}
	log.Printf("Authenticated user %+v", authenticatedUser)
}
```

**Comment by robbiet480** [comment]
I assume you are replacing JWT_TOKEN with a real JWT right?

**Comment by kickbox** [comment]
Things partially work now. Sorry, I was actually sending the JWT_AUTH _KEY specified in the JWT wp-plugin docs. Then I followed this video here https://www.youtube.com/watch?v=Mp7T7x1oxDk, and got to know how to use it properly.

The issue now is that email and capabilities are empty from the Client.Users.Me() function. Any ideas?

**Comment by kickbox** [comment]
Is there a way to get the role of the customer? Can you please share the go code for the same..

**Comment by robbiet480** [comment]
@kickbox You probably need to set `UserListOptions.ListOptions.Context` to `edit` to see those fields as per [the docs](https://developer.wordpress.org/rest-api/reference/users/#retrieve-a-user).
